#!/usr/bin/env zsh
set -euo pipefail

# @description Interactively select and run a shell command.
# @usage str fzf commands

selection=$(
  print -rl -- ${(k)commands} |
  sort -u |
  fzf \
    --print-query \
    --layout=default \
    --border \
    --cycle \
    --height=100% \
    --bind='tab:replace-query' \
    --prompt='Run ❯ '
) || exit

query=$(head -n1 <<<"$selection")
choice=$(tail -n1 <<<"$selection")

cmd="${query:-$choice}"

[[ -n "$cmd" ]] || exit

exec zsh -ic "${cmd}"$'\n''exec zsh -i'
